language: node_js

node_js:
        - 'node'
        - '10'
        - '8'

env:   
        - workerCount=3 timeout=600000  

matrix:   
        fast_finish: true  

install:
          - npm uninstall typescript --no-save   
          - npm uninstall tslint --no-save   
          - npm install
          - npm install --save-dev jest

script: 
        - npm run test
